# Generated by Django 6.1.1 on 2026-09-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_board', models.JSONField(help_text='Original puzzle clues (9x9 grid)')),
                ('solution_board', models.JSONField(help_text='Full solution grid (9x9 grid)')),
                ('current_board', models.JSONField(help_text="User's current in-progress grid (9x9 grid)")),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10)),
                ('session_key', models.CharField(db_index=True, help_text='Django session key', max_length=40)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when puzzle was created')),
                ('is_solved', models.BooleanField(default=False, help_text='Whether the puzzle has been successfully completed')),
            ],
        ),
    ]
